---
- hosts: prod
  name: Deploy on VPS
  no_log: true
  tasks:
    - name: Create all .env.prod file
      ansible.builtin.import_tasks: create-env-prod.yml

    - name: Check if a compose.prod.yml already exists
      ansible.builtin.stat:
        path: ./app/compose.prod.yml
      register: found_compose

    - name: Stop all services
      command:
        cmd: "docker compose -f ./app/compose.prod.yml down"
      when: found_compose.stat.exists

    - name: Get compose.prod.yml
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Spacelocust/for-democracy/main/compose.prod.yml
        dest: ./app/compose.prod.yml
        force: true
        mode: "0660"

    - name: Get Caddyfile
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Spacelocust/for-democracy/main/docker/prod/caddy/Caddyfile
        dest: ./app/Caddyfile
        force: true
        mode: "0660"

    - name: Create and pull compose services
      command:
        cmd: "docker compose -f ./app/compose.prod.yml {{ item }}"
      loop:
        - pull
        - build --force-rm
        - up -d --remove-orphans --force-recreate

    - name: Launch migrations
      command:
        cmd: "docker run --rm -e DATABASE_URL={{ api_database_url }} --network database spacelocust/fd-migrations:latest"

    - name: Launch collector
      command:
        cmd: "docker compose -f ./app/compose.prod.yml exec api fd-democracy collector"

    - name: Clear previous deploy
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: true
