name: Linting Mobile

on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "mobile/**"
      - ".github/workflows/lint-mobile.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-mobile:
    name: Lint Mobile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: mobile/pubspec.yaml

      - name: Copy .env.ci to .env
        run: cp .env.ci .env

      - name: Install dependencies
        run: flutter pub get

      - name: Run lint
        run: flutter analyze --suppress-analytics --no-fatal-infos
